steps:
  - id: 'Run Tests'
    name: gradle:6.6-jdk11
    entrypoint: gradle
    args: ["test"]
    env:
      - 'pg_user=postgres'
      - 'pg_pwd=1qaz!QAZ'
    waitFor: ['-']

  - id: 'Build Jar'
    name: gradle:6.6-jdk11
    entrypoint: gradle
    args: ["build"]
    waitFor: ["Run Tests"]

  - id: 'Deploy on AppEng'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    timeout: '1600s'
    waitFor: ["Build Jar"]
