server:
  port: 8080
  servlet:
    context-path: /api

app:
  datasources:
    first:
      credentials:
        username: ${PG_USER}
        password: ${PG_PWD}
      host: localhost
      port: 5432
      name: poc
      schema: public
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${app.datasources.first.host}:${app.datasources.first.port}/${app.datasources.first.name}?currentSchema=${app.datasources.first.schema}
    second:
      credentials:
        username: ${MYSQL_USER}
        password: ${MYSQL_PWD}
      host: localhost
      port: 3306
      name: poc
      schema: public
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${app.datasources.second.host}:${app.datasources.second.port}/${app.datasources.first.name}?currentSchema=${app.datasources.second.schema}


spring:
  datasource:
    driver-class-name: ${app.datasources.first.driver-class-name}
    name: ${app.datasources.first.name}
    username: ${app.datasources.first.credentials.username}
    password: ${app.datasources.first.credentials.password}
    jdbc-url: ${app.datasources.first.url}     # <------ Crucial to use 'jdbc-url' instead of 'url'
    platform: postgres
    continue-on-error: false

  warehouse-datasource:
    driver-class-name: ${app.datasources.second.driver-class-name}
    name: ${app.datasources.second.name}
    username: ${app.datasources.second.credentials.username}
    password: ${app.datasources.second.credentials.password}
    jdbc-url: ${app.datasources.second.url}    # <------ Crucial to use 'jdbc-url' instead of 'url'
    platform: mysql
    continue-on-error: false


  liquibase:
    enabled: true
    user: ${PG_USER}
    password: ${PG_PWD}
    url: ${app.datasources.first.url}
    change-log: classpath:db/master.yml
