app:
  datasources:
    first:
      host: 35.242.135.116
      port: 5432
      credentials:
        username: ${INSTANCE01_USR}
        password: ${INSTANCE01_PWD}
    second:
      host: 35.195.20.21
      port: 3306
      credentials:
        username: ${INSTANCE02_USR}
        password: ${INSTANCE02_PWD}

spring:
  datasource:
    data-source-properties:
      socketFactory: com.google.cloud.sql.postgres.SocketFactory
      cloudSqlInstance: ${INSTANCE01_NAME}

  warehouse-datasource:
    data-source-properties:
      socketFactory: com.google.cloud.sql.mysql.SocketFactory
      cloudSqlInstance: ${INSTANCE02_NAME}
