service: poc-spring-2-ds-private-ip-and-sm
runtime: java11
env: standard

vpc_access_connector:
  name: "projects/deustchebankpocforgcp-01/locations/europe-west1/connectors/mysql-region-connector"

env_variables:
  SPRING_PROFILES_ACTIVE: "cloud"

manual_scaling:
  instances: 1
