service: poc-spring-2-ds-public-ip
runtime: java11
env: standard

env_variables:
  INSTANCE01_USR: "davide"
  INSTANCE01_PWD: "d4v1d3%3cr3t"
  INSTANCE01_NAME: "deustchebankpocforgcp-01:europe-west2:deutsche-poc-davide-m"
  INSTANCE02_USR: "davide"
  INSTANCE02_PWD: "d4v1d3%3cr3t"
  INSTANCE02_NAME: "deustchebankpocforgcp-01:europe-west1:deutsche-poc-davide-mysql"
  SPRING_PROFILES_ACTIVE: "cloud"

manual_scaling:
  instances: 1
